CREATE SCHEMA IF NOT EXISTS clinica;
USE clinica;

CREATE TABLE IF NOT EXISTS DOCTORS (
    IdDoctors INT PRIMARY KEY AUTO_INCREMENT,
    FIO VARCHAR(45),
    Experience VARCHAR(45),
    Qualification VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PATIENT(
IdPatient INT PRIMARY KEY AUTO_INCREMENT,
SpecialCategory varchar(45),
FIO VARCHAR(45),
GENDER VARCHAR(45),
NumberPhone VARCHAR(45),
Adress VARCHAR(45),
DateBirth VARCHAR(45),
MedicalCard VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS APPOINTMENT(
IdAppointment INT PRIMARY KEY AUTO_INCREMENT,
IdPatient INT,
IdDoctors INT,
Diagnosis VARCHAR(45),
Recipe VARCHAR(45),
Price VARCHAR(45),
Datee Date,
Timee Time,
FOREIGN KEY (IdPatient) REFERENCES PATIENT(IdPatient),
FOREIGN KEY (IdDoctors) REFERENCES DOCTORS(IdDoctors)
);

CREATE TABLE IF NOT EXISTS MAKE_AN_APPOINTMENT(
IdMakeAppointment INT PRIMARY KEY AUTO_INCREMENT,
IdPatient INT,
IdDoctors INT,
Reason VARCHAR(45),
Statuss VARCHAR(45),
Datee DATE,
Timee Time,
FOREIGN KEY (IdPatient) REFERENCES PATIENT(IdPatient),
FOREIGN KEY (IdDoctors) REFERENCES DOCTORS(IdDoctors)
);

-- drop schema if exists PAIDCLINIC;